# Spring Application Name
spring.application.name=Tavolo Platform

# Production specific configurations
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
server.port=${SERVER_PORT:10000}

# JWT Configuration
authorization.jwt.secret=${AUTHORIZATION_JWT_SECRET}
authorization.jwt.expiration.days=${AUTHORIZATION_JWT_EXPIRATION_DAYS}

# CORS Configuration
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:*}